apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: nugs0uikb-go 
  janus-idp.io/tekton: nugs0uikb-go
  backstage.io/kubernetes-id: nugs0uikb-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nugs0uikb-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml