apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nugs0uikb-go
  janus-idp.io/tekton: nugs0uikb-go
  backstage.io/kubernetes-id: nugs0uikb-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nugs0uikb-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
