apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nugs0uikb-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nugs0uikb-go 
  name: nugs0uikb-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nugs0uikb-go 
